name: Terraform State Management

on:
  push:
    branches:
      - main
      - develop # 一時的に追加
  pull_request:
    branches:
      - main

env:
  working-directory: ./terraform
  AZURE_RESOURCE_GROUP: azfunc-cosmosdb
  AZURE_FUNCTIONAPP_NAME: azfunc-cosmosdb-func
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  DOTNET_VERSION: '6.0'

jobs:
  # terraform:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Set up Terraform
  #     uses: hashicorp/setup-terraform@v1
  #     with:
  #       terraform_version: 1.4.0
  #   - name: Create terraform.tfvars file
  #     run: echo $'${{ secrets.TFVARS }}' > terraform.tfvars
  #     working-directory: ${{ env.working-directory }}
  #   - name: Terraform Init
  #     run: terraform init -upgrade
  #           -backend-config="storage_account_name=${{ secrets.STORAGRE_ACOUNT_NAME }}"
  #           -backend-config="container_name=${{ secrets.CONTAINER_NAME }}"
  #           -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
  #     working-directory: ${{ env.working-directory }}
  #   - name: Terraform Plan
  #     run: terraform plan
  #     working-directory: ${{ env.working-directory }}
  #   - name: Terraform Apply
  #     run: terraform apply --auto-approve
  #     working-directory: ${{ env.working-directory }}
  build-and-deploy:
    runs-on: ubuntu-latest
    # needs: terraform
    steps:
    - name: 'Checkout GitHub action'
      uses: actions/checkout@v3
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Get Azure Functions Publish Profile
      id: profile
      run: |
        az functionapp deployment list-publishing-profiles -g ${{ env.AZURE_RESOURCE_GROUP }} -n ${{ env.AZURE_FUNCTIONAPP_NAME }} --xml >> $GITHUB_ENV
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
